---
title: "GG"
---

# Opciones básicas de ggplot2:

De acuerdo con la "gramática de los gráficos", todo gráfico estadístico tiene tres componentes: 
1. Datos (dataframe)
2. Mapeos de las columnas del dataframe a las propiedades isuales del gráfico (x, y, color, tamaño, forma, etc.)
3. Una o varias capas con geometrías (geom_point(), geom_bar(), geom_box())
```{r}
library(DT)
library(ggplot2)
library(plotly)
library(dplyr)
library(leaflet)
library(sf)
library(readxl)
library(tidyverse)
library(ggthemes)
```
```{r}
Estadisticas_Policiales <- 
  readxl::read_excel("C:/Users/DANIEL SARAVIA CRUZ/Downloads/estadsticaspoliciales2022.xlsx")

Estadisticas_Policiales$Fecha <- as.Date(Estadisticas_Policiales$Fecha, format = "%Y-%m-%d")
```

```{r}
#| label: grafico-basico
#| warning: false
#| message: false
#| code-fold: true

# Tabla interactiva del paquete DT

Estadisticas_Policiales %>%
  dplyr::select(Delito,
                Fecha,
                Victima,
                Edad,
                Genero,
                Provincia,
                Canton) %>%
  mutate(Fecha = as.Date(Fecha, format = "%d/%m/%Y")) %>%
  datatable(
    options = list(
      pageLength = 15,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    ),
    colnames = c(
      # encabezados de las columnas
      "Delito",
      "Fecha",
      "Víctima",
      "Edad",
      "Género",
      "Provincia",
      "Cantón"
    )
  )

```
```{r}
#| label: grafico-basico
#| warning: false
#| message: false
#| code-fold: true
Cantidad_de_delito_por_tipo <-
  Estadisticas_Policiales %>%
  count(Delito) %>%
  ggplot(aes(x = reorder(Delito, n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por tipo de delito") +
  xlab("Tipo de Delito") +
  ylab("Cantidad") +
  coord_flip() +
  theme_hc()

Cantidad_de_delito_por_tipo %>%
  ggplotly() %>%
  config(locale = "es")
```

